#!/bin/bash

loggedInUser="$(
	/usr/bin/python -c "$(
		cat <<-EOF
			from SystemConfiguration import SCDynamicStoreCopyConsoleUser
			import sys
			username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]
			username = [username,""][username in [u"loginwindow", None, u""]]
			sys.stdout.write(username + "\n")
		EOF
	)"	
)"

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

launchctl asuser "${loggedInUser}" "$scriptDir/applet"
